version: "3.9"
services: 
  node:
    container_name: 'load-balancer'
    build: .
    env_file: 
      - ./nginx.config
    volumes: 
      - .:/etc/nginx
  nginx:
    container_name: 'nginx_proxy'
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - node
    ports: 
      - 80:80
      - 8080:8080
